In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

# Google Colab Setup 

Please run the code below to mount drive if you are running on colab.

Please ignore if you are running on your local machine.

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# %cd /content/drive/MyDrive/MiniGPT/

# Language Modeling and Transformers

The project will consist of two broad parts. 

1. **Baseline Generative Language Model**: We will train a simple Bigram language model on the text data. We will use this model to generate a mini story. 
2. **Implementing Mini GPT**: We will implement a mini version of the GPT model layer by layer and attempt to train it on the text data. You will then load pretrained weights provided and generate a mini story. 

## Some general instructions 

1. Please keep the name of layers consistent with what is requested in the `model.py` file for each layer, this helps us test in each function independently. 
2. Please check to see if the bias is to be set to false or true for all linear layers (it is mentioned in the doc string)
3. As a general rule please read the docstring well, it contains information you will need to write the code. 
4. All configs are defined in `config.py` for the first part while you are writing the code do not change the values in the config file since we use them to test. Once you have passed all the tests please feel free to vary the parameter as you please.
5. You will need to fill in the `train.py` and run it to train the model. If you are running into memory issues please feel free to change the `batch_size` in the `config.py` file. If you are working on Colab please make sure to use the GPU runtime and feel free to copy over the training code to the notebook. 

In [4]:
# !pip install numpy torch tiktoken wandb einops # Install all required packages

In [5]:
%load_ext autoreload
%autoreload 2

In [6]:
import torch
import tiktoken

In [7]:
from model import BigramLanguageModel, SingleHeadAttention, MultiHeadAttention, FeedForwardLayer, LayerNorm, TransformerLayer, MiniGPT
from config import BigramConfig, MiniGPTConfig
import tests

In [8]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [9]:
path_to_bigram_tester = "./pretrained_models/bigram_tester.pt" # Load the bigram model with name bigram_tester.pt
path_to_gpt_tester = "./pretrained_models/minigpt_tester.pt" # Load the gpt model with name minigpt_tester.pt

##  Bigram Language Model (10 points)

A bigram language model is a type of probabilistic language model that predicts a word given the previous word in the sequence. The model is trained on a text corpus and learns the probability of a word given the previous word.



### Implement the Bigram model (5 points)

Please complete the `BigramLanguageModel` class in model.py. We will model a Bigram language model using a simple MLP with one hidden layer. The model will take in the previous word index and output the logits over the vocabulary for the next word.

In [10]:
# Test implementation for Bigram Language Model
model = BigramLanguageModel(BigramConfig)
tests.check_bigram(model,path_to_bigram_tester, device)

'TEST CASE PASSED!!!'

### Training the Bigram Language Model (2.5 points)

Complete the code in `train.py` to train the Bigram language model on the text data. Please provide plots for both the training and validation in the cell below.

Some notes on the training process:

1. You should be able to train the model slowly on your local machine.
2. Training it on Colab will help with speed.
3.  <span style="color:red">To get full points for this section it is sufficient to show that the loss is decreasing over time</span>. You should see it saturate to a value close to around 5-6 but as long as you see it decreasing then saturating you should be good.
4. Please log the loss curves either on wandb, tensorboard or any other logger of your choice and please attach them below.

### Train and Valid Plots

In [1]:
from train import *
model = BigramLanguageModel(BigramConfig)
run = train_bigram(model)

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: anony-mouse-153805274587626300. Use `wandb login --relogin` to force relogin


number of trainable parameters: 3.27M
Training iterations: 10000/62500 - loss=4.996214866638184, val_loss=4.608631610870361
Training iterations: 20000/62500 - loss=4.381487846374512, val_loss=4.309932708740234
Training iterations: 30000/62500 - loss=4.076179027557373, val_loss=3.947111129760742
Training iterations: 40000/62500 - loss=4.1110100746154785, val_loss=4.182976245880127
Training iterations: 50000/62500 - loss=3.656944990158081, val_loss=4.060536861419678
Training iterations: 60000/62500 - loss=3.8277087211608887, val_loss=3.647256851196289


### Generation (2.5 points)

Complete the code in the `generate` method of the Bigram class and generate a mini story using the trained Bigram language model. The model will take in the previous word index and output the next word index.

Start with the following seed sentence: 
    
    `"once upon a time"`
    

In [2]:
tokenizer = tiktoken.get_encoding("gpt2")

NameError: name 'tiktoken' is not defined

In [ ]:
gen_sent = "Once upon a time"
gen_tokens = torch.tensor(tokenizer.encode(gen_sent))
print("Generating text starting with:", gen_tokens.shape)
gen_tokens = gen_tokens.to(device)
model.eval()
print(
    tokenizer.decode(
        model.generate(gen_tokens, max_new_tokens=200).squeeze().tolist()
    )
)

### Observation and Analysis

Please answer the following questions. 

1. What can we say about the generated text in terms of grammar and coherence? 
2. What are the limitations of the Bigram language model?
3. If the model is scaled with more parameters do you expect the bigram model to get substantially better? Why or why not?

## Mini GPT (90 points)

We will not implement a decoder style transformer model like we discussed in lecture, which is a scaled down version of the [GPT model](https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf). 

All the model components follow directly from the original [Attention is All You Need](https://arxiv.org/abs/1706.03762) paper. The only difference is we will use prenormalization and learnt positional embeddings instead of fixed ones. But you will not need to worry about these details!

We will now implement each layer step by step checking if it is implemented correctly in the process. We will finally put together all our layers to get a fully fledged GPT model. 

<span style="color:red">Later layers might depend on previous layers so please make sure to check the previous layers before moving on to the next one.</span>

### Single Head Causal Attention (20 points)

We will first implement the single head causal attention layer. This layer is the same as the scaled dot product attention layer but with a causal mask to prevent the model from looking into the future.

Recall that Each head has a Key, Query and Value Matrix and the scaled dot product attention is calculated as : 

\begin{equation}
\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V
\end{equation}

where $d_k$ is the dimension of the key matrix.

Figure below from the original paper shows how the layer is to be implemented.

![image](./Images/Single_Head.png)

Image credits: [Attention is All You Need Paper](https://arxiv.org/abs/1706.03762)

In [35]:
model = SingleHeadAttention(MiniGPTConfig.embed_dim, MiniGPTConfig.embed_dim//4, MiniGPTConfig.embed_dim//4) # configs are set as such for testing do not modify
tests.check_singleheadattention(model, path_to_gpt_tester, device)

'TEST CASE PASSED!!!'

In [ ]:
import numpy as np
data_file = "./test_cases.npz"
key = "singleheadattention"
data = np.load(data_file)
old_input = torch.from_numpy(data[key + "_input"]).to("cuda")

In [286]:
model = SingleHeadAttention(MiniGPTConfig.embed_dim, MiniGPTConfig.embed_dim//4, MiniGPTConfig.embed_dim//4) # configs are set as such for testing do not modify
print(model.key.weight)

Parameter containing:
tensor([[-0.1049, -0.0179, -0.0841,  ...,  0.0472, -0.1225,  0.0602],
        [-0.0907, -0.0397,  0.0588,  ...,  0.1060, -0.0155,  0.0987],
        [-0.0784,  0.1234, -0.1045,  ...,  0.1161,  0.0936,  0.1105],
        ...,
        [ 0.0870,  0.0428,  0.0964,  ..., -0.0993,  0.0404,  0.0775],
        [-0.1151,  0.0202, -0.0079,  ...,  0.1085, -0.1077,  0.0679],
        [ 0.1195, -0.0320,  0.0077,  ..., -0.0922,  0.0088,  0.0459]],
       requires_grad=True)


In [287]:
ckpt = torch.load(path_to_gpt_tester, map_location=device)
print(model.key.weight.data)
a = model.key.weight.data.clone()
with torch.no_grad():

    model.key.weight.copy_(
        ckpt["model_state_dict"]["transformer_layers.0.attention.head_0.key.weight"]
    )
    model.query.weight.copy_(
        ckpt["model_state_dict"][
            "transformer_layers.0.attention.head_0.query.weight"
        ]
    )
    model.value.weight.copy_(
        ckpt["model_state_dict"][
            "transformer_layers.0.attention.head_0.value.weight"
        ]
    )
    model.causal_mask.copy_(
        ckpt["model_state_dict"][
            "transformer_layers.0.attention.head_0.causal_mask"
        ]
    )
print(model.key.weight.data)
((a - model.key.weight.data) == 0).all()

tensor([[-0.1049, -0.0179, -0.0841,  ...,  0.0472, -0.1225,  0.0602],
        [-0.0907, -0.0397,  0.0588,  ...,  0.1060, -0.0155,  0.0987],
        [-0.0784,  0.1234, -0.1045,  ...,  0.1161,  0.0936,  0.1105],
        ...,
        [ 0.0870,  0.0428,  0.0964,  ..., -0.0993,  0.0404,  0.0775],
        [-0.1151,  0.0202, -0.0079,  ...,  0.1085, -0.1077,  0.0679],
        [ 0.1195, -0.0320,  0.0077,  ..., -0.0922,  0.0088,  0.0459]])
tensor([[ 0.0100, -0.0674, -0.0818,  ...,  0.1394, -0.0457, -0.0254],
        [-0.0522, -0.0628, -0.0789,  ..., -0.1113,  0.0129,  0.0384],
        [ 0.0013,  0.0920, -0.0182,  ...,  0.0385,  0.0361, -0.0939],
        ...,
        [ 0.0406, -0.0487, -0.0809,  ...,  0.0543, -0.0311,  0.0135],
        [ 0.0136, -0.0598, -0.0318,  ...,  0.2232, -0.0556, -0.0097],
        [-0.0166,  0.0084, -0.1420,  ...,  0.1538, -0.0861, -0.0046]])


tensor(False)

In [288]:
model.train()
model.to(device)
model(old_input)

K=tensor([[[ 0.3168, -0.8926,  0.4330,  ..., -0.4311, -0.1072, -0.2947],
         [ 0.6227,  0.1689, -0.0955,  ...,  0.6620,  0.5843,  0.8092],
         [ 0.4324,  0.4574, -0.8476,  ...,  0.1985,  0.0189, -0.2356],
         ...,
         [ 0.0211, -0.0673, -0.6237,  ...,  0.5999,  0.2107,  0.2072],
         [-0.0892,  0.0916,  2.1027,  ...,  0.4371, -0.1155,  0.8550],
         [ 0.2574,  0.8846, -0.0964,  ...,  0.0833, -0.6097, -0.2315]],

        [[ 0.0034, -0.3145, -0.0900,  ...,  0.0314,  0.2440,  0.0850],
         [ 0.0691, -0.7475, -0.2158,  ..., -0.6004,  0.0884, -0.5879],
         [ 0.0668,  0.4437,  0.0940,  ...,  0.1309,  0.2482,  0.2645],
         ...,
         [-0.1654,  0.1392,  0.4341,  ..., -0.2398, -0.0333, -0.6826],
         [ 0.5554, -0.1345, -0.8010,  ..., -0.1131,  0.4770,  0.0866],
         [ 0.0456, -0.1974,  0.8776,  ...,  0.1746,  0.5212,  0.4142]],

        [[ 0.3289, -0.2587, -0.3318,  ..., -0.0373,  0.4712,  0.2371],
         [ 0.5680,  0.9734, -0.6693,  ..., 

tensor([[[-2.3534e-01,  4.4160e-01,  2.4712e-01,  ..., -4.3161e-01,
          -6.3012e-02,  9.5099e-02],
         [-2.4021e-01,  1.8888e-01,  2.2522e-01,  ..., -2.7357e-01,
           4.1498e-02,  2.1865e-01],
         [-1.7100e-01,  1.5196e-01,  2.0559e-01,  ..., -2.9223e-01,
           9.6958e-02,  1.3514e-01],
         ...,
         [-1.7518e-01,  8.0654e-02,  1.4199e-01,  ..., -1.2506e-01,
           7.4819e-02,  1.4043e-01],
         [-1.6505e-01,  5.2442e-02,  3.1687e-02,  ..., -1.2153e-01,
           1.2633e-03,  4.5715e-02],
         [-1.3623e-01,  4.5516e-02, -7.6407e-03,  ..., -6.6783e-02,
           5.3385e-04,  5.4808e-03]],

        [[ 1.0668e-01, -1.7895e-01,  2.5020e-01,  ...,  4.9146e-01,
          -1.2372e-01, -1.0415e-01],
         [ 1.7492e-01,  2.6231e-02,  1.2033e-01,  ...,  1.8411e-01,
          -3.2396e-01,  4.2061e-02],
         [ 1.0217e-01,  2.1042e-01,  1.3217e-01,  ...,  4.6757e-02,
          -4.3482e-02,  2.7867e-02],
         ...,
         [ 2.1304e-01,  7

In [281]:
old_input@model.key.weight.data.transpose(-1,-2)

tensor([[[ 0.3168, -0.8926,  0.4330,  ..., -0.4311, -0.1072, -0.2947],
         [ 0.6227,  0.1689, -0.0955,  ...,  0.6620,  0.5843,  0.8092],
         [ 0.4324,  0.4574, -0.8476,  ...,  0.1985,  0.0189, -0.2356],
         ...,
         [ 0.0211, -0.0673, -0.6237,  ...,  0.5999,  0.2107,  0.2072],
         [-0.0892,  0.0916,  2.1027,  ...,  0.4371, -0.1155,  0.8550],
         [ 0.2574,  0.8846, -0.0964,  ...,  0.0833, -0.6097, -0.2315]],

        [[ 0.0034, -0.3145, -0.0900,  ...,  0.0314,  0.2440,  0.0850],
         [ 0.0691, -0.7475, -0.2158,  ..., -0.6004,  0.0884, -0.5879],
         [ 0.0668,  0.4437,  0.0940,  ...,  0.1309,  0.2482,  0.2645],
         ...,
         [-0.1654,  0.1392,  0.4341,  ..., -0.2398, -0.0333, -0.6826],
         [ 0.5554, -0.1345, -0.8010,  ..., -0.1131,  0.4770,  0.0866],
         [ 0.0456, -0.1974,  0.8776,  ...,  0.1746,  0.5212,  0.4142]],

        [[ 0.3289, -0.2587, -0.3318,  ..., -0.0373,  0.4712,  0.2371],
         [ 0.5680,  0.9734, -0.6693,  ..., -0

Please complete the `SingleHeadAttention` class in `model.py`

### Multi Head Attention (10 points)

Now that we have a single head working, we will now scale this across multiple heads, remember that with multihead attention we compute perform head number of parallel attention operations. We then concatenate the outputs of these parallel attention operations and project them back to the desired dimension using an output linear layer.

Figure below from the original paper shows how the layer is to be implemented.

![image](./Images/MultiHead.png)

Image credits: [Attention is All You Need Paper](https://arxiv.org/abs/1706.03762)

Please complete the `MultiHeadAttention` class in `model.py` using the `SingleHeadAttention` class implemented earlier. 

In [ ]:
model = MultiHeadAttention(MiniGPTConfig.embed_dim, MiniGPTConfig.num_heads)

tests.check_multiheadattention(model, path_to_gpt_tester, device)

### Feed Forward Layer (5 points)

As discussed in lecture, the attention layer is completely linear, in order to add some non-linearity we add a feed forward layer. The feed forward layer is a simple two layer MLP with a GeLU activation in between.

Please complete the `FeedForwardLayer` class in `model.py`

In [ ]:
model = FeedForwardLayer(MiniGPTConfig.embed_dim)

tests.check_feedforward(model, path_to_gpt_tester, device)

### LayerNorm (10 points)

We will now implement the layer normalization layer. Layernorm is used across the model to normalize the activations of the previous layer. Recall that the equation for layernorm is given as:

\begin{equation}

\text{LayerNorm}(x) = \frac{x - \mu}{\sqrt{\sigma^2 + \epsilon}} \odot \gamma + \beta

\end{equation}

With the learnable parameters $\gamma$ and $\beta$. 

Remember that unlike batchnorm we compute statistics across the feature dimension and not the batch dimension, hence we do not need to keep track of running averages.

Please complete the `LayerNorm` class in `model.py`

In [ ]:
model = LayerNorm(MiniGPTConfig.embed_dim)
tests.check_layernorm(model, path_to_gpt_tester, device)

### Transformer Layer (15 points)

We have now implemented all the components of the transformer layer. We will now put it all together to create a transformer layer. The transformer layer consists of a multi head attention layer, a feed forward layer and two layer norm layers.

Please use the following order for each component (Varies slightly from the original attention paper):
1. LayerNorm
2. MultiHeadAttention
3. LayerNorm
4. FeedForwardLayer

Remember that the transformer layer also has residual connections around each sublayer.

The below figure shows the structure of the transformer layer you are required to implement.

![prenorm_transformer](./Images/Prenorm.png)

Image Credit : [CogView](https://arxiv.org/pdf/2105.13290)

Implement the `TransformerLayer` class in `model.py`

In [ ]:
model =  TransformerLayer(MiniGPTConfig.embed_dim, MiniGPTConfig.num_heads)
tests.check_transformer(model, path_to_gpt_tester, device)

### Putting it all together : MiniGPT (15 points)

We are now ready to put all our layers together to build our own MiniGPT! 

The MiniGPT model consists of an embedding layer, a positional encoding layer and a stack of transformer layers. The output of the transformer layer is passed through a linear layer (called head) to get the final output logits. Note that in our implementation we will use [weight tying](https://arxiv.org/abs/1608.05859) between the embedding layer and the final linear layer. This allows us to save on parameters and also helps in training.

Implement the `MiniGPT` class in `model.py`

In [ ]:
model = MiniGPT(MiniGPTConfig)
tests.check_miniGPT(model, path_to_gpt_tester, device)

### Attempt at training the model (5 points)

We will now attempt to train the model on the text data. We will use the same text data as before. Please scale down the model parameters in the config file to a smaller value to make training feasible. 

Use the same training script we built for the Bigram model to train the MiniGPT model. If you implemented it correctly it should work just out of the box!

**NOTE** : We will not be able to train the model to completion in this assignment. Unfortunately, without access to a relatively powerful GPU, training a large enough model to see good generation is not feasible. However, you should be able to see the loss decreasing over time. <span style="color:red">To get full points for this section it is sufficient to show that the loss is decreasing over time</span>. You do not need to run this for more than 5000 iterations or 1 hour of training.

### Train and Valid Plots


** Show the training and validation loss plots **

### Generation (5 points)


Perform generation with the model that you trained. Copy over the generation function you used for the Bigram model not the `miniGPT` class and generate a mini story using the same seed sentence. 

    `"once upon a time"`

Please answer the following questions. 

1. What can we say about the generated text in terms of grammar and coherence? 
2. If the model is scaled with more parameters do you expect the GPT model to get substantially better? Why or why not?

### Scaling up the model (5 points)

To show that scale indeed will help the model learn we have trained a scaled up version of the model you just implemented. We will load the weights of this model and generate a mini story using the same seed sentence. Note that if you have implemented the model correctly just scaling the parameters and adding a few bells and whistles to the training script will results in a model like the one we will load now. 

In [ ]:
from model import MiniGPT
from config import MiniGPTConfig

In [ ]:
path_to_trained_model = "pretrained_models/best_train_loss_checkpoint.pth"

In [ ]:
ckpt = torch.load(path_to_trained_model, map_location=device) # remove map location if using GPU

In [ ]:
# Set the configs for scaled model 
MiniGPTConfig.context_length = 512
MiniGPTConfig.embed_dim = 256
MiniGPTConfig.num_heads = 16
MiniGPTConfig.num_layers = 8

In [ ]:
# Load model from checkpoint
model = MiniGPT(MiniGPTConfig)
model.load_state_dict(ckpt["model_state_dict"])

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")

In [ ]:
model.to(device)
gen_sent = "Once upon a time"
gen_tokens = torch.tensor(tokenizer.encode(gen_sent))
print("Generating text starting with:", gen_tokens.shape)
gen_tokens = gen_tokens.to(device)
model.eval()
print(
    tokenizer.decode(
        model.generate(gen_tokens, max_new_tokens=200).squeeze().tolist()
    )
)

## Bonus (5 points)

The following are some open ended questions that you can attempt if you have time. Feel free to propose your own as well if you have an interesting idea. 

1. The model we have implemented is a decoder only model. Can you implement the encoder part as well? This should not be too hard to do since most of the layers are already implemented.
2. What are some improvements we can add to the training script to make training more efficient and faster? Can you concretely show that the improvements you made help in training the model better?
3. Can you implement a beam search decoder to generate the text instead of greedy decoding? Does this help in generating better text?
4. Can you further optimize the model architecture? For example, can you implement [Multi Query Attention](https://arxiv.org/abs/1911.02150) or [Grouped Query Attention](https://arxiv.org/pdf/2305.13245) to improve the model performance?